# Generated by Django 4.1 on 2023-05-28 18:57

import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_remove_hotel_price_alter_hotel_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='State',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='discount',
        ),
        migrations.AddField(
            model_name='gallery',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galley', to='hotels.hotel', verbose_name='هتل'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(blank=True, upload_to='hotels/gallery', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='address',
            field=models.CharField(max_length=600, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='city',
            field=models.CharField(max_length=200, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='cover',
            field=models.ImageField(blank=True, upload_to='hotels/covers/', verbose_name='تصویر شاخص'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام هتل'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='status',
            field=models.CharField(choices=[('yes', 'Active'), ('no', 'Inactive')], max_length=3, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش'),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_Type', models.CharField(choices=[('1', 'one'), ('2', 'two'), ('3', 'three'), ('4', 'four'), ('5', 'five')], max_length=1, verbose_name='نوع اتاق')),
                ('price', models.DecimalField(decimal_places=0, max_digits=6, verbose_name='قیمت')),
                ('status', models.CharField(choices=[('yes', 'Active'), ('no', 'Inactive')], max_length=3, verbose_name='وضعیت')),
                ('breakfast', models.BooleanField(default=True, verbose_name='صبحانه')),
                ('extra_bed', models.BooleanField(default=False, verbose_name='تخت اضافه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='hotels.hotel', verbose_name='هتل')),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='تخفیف')),
                ('start_date', models.DateTimeField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateTimeField(verbose_name='تاریخ پایان')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount', to='hotels.hotel', verbose_name='هتل')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount', to='hotels.room', verbose_name='اتاق')),
            ],
        ),
        migrations.AddField(
            model_name='hotel',
            name='state',
            field=models.CharField(default=1, max_length=200, verbose_name='استان'),
            preserve_default=False,
        ),
    ]
