# Generated by Django 4.1 on 2023-05-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_city_remove_hotel_state_alter_discount_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='state',
            field=models.CharField(choices=[('AL', 'البرز'), ('AR', 'اردبیل'), ('EA', 'آدربایجان غربی'), ('WE', 'آذربایجان شرقی'), ('BU', 'بوشهر'), ('CH', 'چهارمحال و بختیاری'), ('FA', 'فارس'), ('GI', 'گیلان'), ('GO', 'گلستان'), ('HA', 'همدان'), ('HR', 'هرمزگان'), ('IL', 'ایلام'), ('IS', 'اصفحان'), ('KE', 'کرمان'), ('KZ', 'کرمانشاه'), ('KH', 'خوزستان'), ('KB', 'کهگلویه و بویراحمد'), ('KR', 'کردستان'), ('LO', 'لرستان'), ('MK', 'مرکزی'), ('MA', 'مازندران'), ('NK', 'خراسان شمالی'), ('QA', 'قزوین'), ('QO', 'قم'), ('RK', 'خراسان رضوی'), ('SB', 'سیستان و بلوچستان'), ('SK', 'خراسان جنوبی'), ('SM', 'سمنان'), ('TE', 'تهران'), ('YA', 'یزد'), ('ZA', 'رنجان')], max_length=2, verbose_name='استان'),
        ),
    ]
