# Generated by Django 4.1 on 2023-05-29 19:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0007_alter_city_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='class_hotel',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='کلاس هتل (چند ستاره)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='city',
            name='state',
            field=models.CharField(choices=[('TE', 'تهران'), ('RK', 'خراسان رضوی'), ('FA', 'فارس'), ('HR', 'هرمزگان'), ('IS', 'اصفهان'), ('QO', 'قم'), ('AL', 'البرز'), ('AR', 'اردبیل'), ('EA', 'آدربایجان غربی'), ('WE', 'آذربایجان شرقی'), ('BU', 'بوشهر'), ('CH', 'چهارمحال و بختیاری'), ('GI', 'گیلان'), ('GO', 'گلستان'), ('HA', 'همدان'), ('IL', 'ایلام'), ('KE', 'کرمان'), ('KZ', 'کرمانشاه'), ('KH', 'خوزستان'), ('KB', 'کهگلویه و بویراحمد'), ('KR', 'کردستان'), ('LO', 'لرستان'), ('MK', 'مرکزی'), ('MA', 'مازندران'), ('NK', 'خراسان شمالی'), ('QA', 'قزوین'), ('SB', 'سیستان و بلوچستان'), ('SK', 'خراسان جنوبی'), ('SM', 'سمنان'), ('YA', 'یزد'), ('ZA', 'رنجان')], max_length=2, verbose_name='استان'),
        ),
    ]
