# Generated by Django 4.1 on 2023-05-30 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0008_hotel_class_hotel_alter_city_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=8, verbose_name='قیمت (تومان)'),
        ),
    ]
