# Generated by Django 4.1 on 2023-05-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('man', 'Man'), ('woman', 'Woman')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='D:\\Project\\Django\\Hotel Reservation\\Template\\simple_bookstore\\media\\avatars\\default.png', null=True, upload_to='avatars/'),
        ),
    ]
