# Generated by Django 4.2.2 on 2023-06-06 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_gender_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='D:\\Project\\Django\\Hotel Reservation\\Template\\hotel_reservation\\media\\avatars\\default.png', null=True, upload_to='avatars/'),
        ),
    ]
